name: build

on:
  workflow_call:
  push:
    branches:
      - main

jobs: #jobs 는 여러개의 step들로 이루어집니다.
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # workflow가 repository를 접근할 수 있게 checkout합니다.

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wayinwayne/action-test:latest
          file: /Dockerfile
